### PR TITLE
Detect and recover from ping timeouts

### PR DESCRIPTION
**Pull request by philip-peterson**
I've re-added support for ping timeout detection and recovery (relevant tickets: #76, #214, #176, #375). This has been tested by hand, but haven't been able to run it in a real environment (and won't, since my team no longer uses IRC), so beware there may yet be bugs.

I decided to err on the side of too "wordy" of code in order to allow easier testing later on and, hopefully, more readability. Feedback on how the code is structured and what could be done better/differently would be much appreciated.

### CODE REVIEW

**Comment by jirwin** [comment]
This looks great. I'll try and build a test for it, and work on getting it merged.

**Comment by philip-peterson** [comment]
Let me know if I can be of assistance!

**Comment by Starefossen** [comment]
Looking forward to this!

**Comment by jirwin** [comment]
@philip-peterson if you could, rebasing this would make things a lot easier for me!

**Comment by vBm** [comment]
rebase and squash ! :P

**Comment by philip-peterson** [comment]
@jirwin @vBm Okay, it's rebased+squashed, new revision number is c91436f98cd49a5aefcd1f7287bef120519f5998 . Let me know if I can do anything else!

**Comment by jirwin** [comment]
+1

**Comment by jirwin** [comment]
Thanks! I'm planning on doing the next release in a week where this will land.

**Comment by FruitieX** [comment]
Awesome! [This has been a problem in teleirc](https://github.com/FruitieX/teleirc/issues/41), and we join in on eagerly awaiting the new release. :+1:

**Pull request merged**
