### PR TITLE
fix(deps): Upgrade node-icu to 0.1.0 for v0.12 support.

### PR DESCRIPTION
**Pull request by jirwin**

### CODE REVIEW

**Comment by jirwin** [comment]
Fixes #332

**Comment by vBm** [comment]
#328 can be also closed.

**Comment by alexandernst** [comment]
Can this be merged and a patch version released? Node 0.12 is now upgraded in most distros and thus breaking this lib.

**Comment by jirwin** [comment]
I'd like to cut a new release this week. There are still some other issues preventing the lib from working on 0.12 that'll need to be handled.

**Comment by feross** [comment]
Any chance you could cut a release? Thanks!

**Comment by feross** [comment]
Ping. We still can't use this on node 0.12 until you publish a new version. Thanks!

**Comment by jirwin** [comment]
I'll cut a new release tomorrow!

**Comment by feross** [comment]
Awesome, thanks.

**Comment by jirwin** [comment]
@feross I've published version `0.3.12`

**Comment by feross** [comment]
awesome, thanks!

**Pull request merged**
