### PR TITLE
WEBIRC support minified

### PR DESCRIPTION
**Pull request by Trinitas**
Webirc is used for multiple users to connect from your node server to irc.
Get the users ip and hostname and send it like this:
``webirc = {"pass":"WebIrcPassWord","host":"my.host.com", "ip":"123.123.12.12"};``
How to configure your server for Webirc can also be found in your irc server dokumentation.

### CODE REVIEW

**Comment by apeiron** [comment]
Is there a server that I can connect to to test this with?

**Comment by Trinitas** [comment]
well it works for me and if there is a problem i'm sure someone will fix it

**Comment by apeiron** [comment]
I'm sure it does work for you, but I feel uncomfortable committing
code I have no way of testing.

**Comment by Trinitas** [comment]
test connecting whit this

var webirc = {"pass":"myPass","host":"www.mySpoofedHostAndIp.com", "ip":"192.168.1.4"};
var opts = {
	webirc: webirc,
	port: 6666
}
var client = new irc.Client('irc.letsbubble.se', 'test',opts,{
});

**Comment by Trinitas** [comment]
now i'm done

**Comment by apeiron** [comment]
I'm a little unclear on why this needs to be part of node-irc and
can't be handled in your code via a `registered` event handler. Can
you clarify, please?

**Comment by Trinitas** [comment]
If you have a node irc server that people connect to you want the clients ip
 not the node irc server ip

**Comment by revmischa** [comment]
Yeah it's pretty old lol. Want me to fix it?

**Comment by Trinitas** [comment]
Fix the ci build fail? Sure

**Comment by jirwin** [comment]
Yeah, we just added linting with the CI, so you'll need to rebase.

**Comment by Trinitas** [comment]
Last time i tried to rebase i accidently removed the patch

**Comment by revmischa** [comment]
Ugh.

CONFLICT (modify/delete): docs/API.rst deleted in remove old files for a clean slate and modified in HEAD. Version HEAD of docs/API.rst left in tree.

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add/rm <file>..." as appropriate to mark resolution)

        deleted by them: docs/API.rst
        deleted by them: lib/irc.js

**Comment by Trinitas** [comment]
I'm on Windows and only uses Web github but i will try fix it later or fix a new pull

**Pull request closed without merging**
