### PR TITLE
Respect opt.messageSplit when calculating message length

### PR DESCRIPTION
**Pull request by LinuxMercedes**
At some point this got dropped out of the calculations.

### CODE REVIEW

**Comment by jirwin** [comment]
@LinuxMercedes Can you add a test for this please?

**Comment by LinuxMercedes** [comment]
I'm really unsure what I could test with this that isn't already covered in this test: https://github.com/martynsmith/node-irc/blob/master/test/test-irc.js#L69

**Comment by LinuxMercedes** [comment]
I went ahead and rebased this and re-ran the tests; I think it should all work now.

**Comment by ekmartin** [comment]
@jirwin - do you have any plans of merging this? Would be really useful!

**Comment by euank** [comment]
Ping, any reason this isn't merged @jirwin? Would be helpful for me too!

**Comment by jirwin** [comment]
Just merged, I'll work on a new release here shortly.

**Comment by ekmartin** [comment]
Thanks!

**Comment by jirwin** [comment]
This is released on node-irc 0.5.1

**Pull request merged**
