### PR TITLE
SSL netError debug

### PR DESCRIPTION
**Pull request by Trinitas**
no comment

### CODE REVIEW

**Comment by jirwin** [comment]
This should only happen when debugging is enabled.

**Comment by jirwin** [comment]
+1 Cool. Thanks.

**Comment by jirwin** [comment]
Can you squash your commits, and use a more meaningful commit message please?

**Comment by Trinitas** [comment]
There is no dokumentation how to "squash" when using web github so sadly no i can't

**Comment by apeiron** [comment]
We provide a link to instructions for this in the CONTRIBUTING.md
file, which github asks you to read before filing pull requests.
Please have a look at
https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request (ignore
the edx-specific bits).

**Comment by Trinitas** [comment]
I have read it before and i still don't have a git command console and have no time learning how to pass git commands from it. I'm still using github.com Website. So no commands and no readme files says how to do it. But! I sent a message to github and asked if there is a way from the browser so I will return when i get an answer

**Comment by jirwin** [comment]
@Trinitas I duplicated your change in #307. Closing this in favor of that.

**Pull request closed without merging**
